spring.application.name=seochang-church
spring.profiles.include=secret

server.port=8080

# PostgreSQL Database Settings (Credentials moved to application-secret.properties)
spring.datasource.url=jdbc:postgresql://localhost:5432/seochang_church?currentSchema=seochang_church_db
spring.datasource.username=seochang_church
# spring.datasource.password=

# JPA (Hibernate) Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=seochang_church_db
spring.jpa.properties.hibernate.default_batch_fetch_size=100

# File Upload Settings
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=100MB 